// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: svc_config.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_GetBotConfig_FullMethodName            = "/svcpb.ConfigService/GetBotConfig"
	ConfigService_GetOperBotConfig_FullMethodName        = "/svcpb.ConfigService/GetOperBotConfig"
	ConfigService_GetUserMasterKey_FullMethodName        = "/svcpb.ConfigService/GetUserMasterKey"
	ConfigService_WidgetNewToken_FullMethodName          = "/svcpb.ConfigService/WidgetNewToken"
	ConfigService_WidgetParseToken_FullMethodName        = "/svcpb.ConfigService/WidgetParseToken"
	ConfigService_WidgetNewCode_FullMethodName           = "/svcpb.ConfigService/WidgetNewCode"
	ConfigService_WidgetParseCode_FullMethodName         = "/svcpb.ConfigService/WidgetParseCode"
	ConfigService_WidgetParseExpiredToken_FullMethodName = "/svcpb.ConfigService/WidgetParseExpiredToken"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService — gRPC service for inter-service communication with Landing.
// Authorization: metadata header "x-service-key" must contain the service key
// stored in app_config under "svc.service_key".
type ConfigServiceClient interface {
	// GetBotConfig returns decrypted Telegram bot settings.
	GetBotConfig(ctx context.Context, in *GetBotConfigRequest, opts ...grpc.CallOption) (*BotConfigResponse, error)
	GetOperBotConfig(ctx context.Context, in *GetBotConfigRequest, opts ...grpc.CallOption) (*BotConfigResponse, error)
	// GetUserMasterKey returns the decrypted User MasterKey from Landing's in-memory cache.
	// The key is available only after the user has logged in at least once since the last
	// Landing restart. Returns codes.Unavailable if the key is not in cache.
	// The caller is responsible for deciding how to handle the unavailable case.
	GetUserMasterKey(ctx context.Context, in *GetUserMasterKeyRequest, opts ...grpc.CallOption) (*UserMasterKeyResponse, error)
	// WidgetNewToken generates a new token for the widget_service based on the provided data.
	WidgetNewToken(ctx context.Context, in *WidgetTokenData, opts ...grpc.CallOption) (*WidgetRawToken, error)
	// WidgetParseToken parses the widget_service raw token and returns the associated data.
	WidgetParseToken(ctx context.Context, in *WidgetRawToken, opts ...grpc.CallOption) (*WidgetTokenData, error)
	// WidgetNewCode sign and get new widget code.
	WidgetNewCode(ctx context.Context, in *WidgetCodeData, opts ...grpc.CallOption) (*WidgetRawToken, error)
	// WidgetParseCode check signature and return climes from widget code.
	WidgetParseCode(ctx context.Context, in *WidgetRawToken, opts ...grpc.CallOption) (*WidgetCodeData, error)
	// WidgetParseExpiredToken parses the expired token and returns valid token
	WidgetParseExpiredToken(ctx context.Context, in *WidgetRawToken, opts ...grpc.CallOption) (*WidgetTokenData, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetBotConfig(ctx context.Context, in *GetBotConfigRequest, opts ...grpc.CallOption) (*BotConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetBotConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetOperBotConfig(ctx context.Context, in *GetBotConfigRequest, opts ...grpc.CallOption) (*BotConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetOperBotConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetUserMasterKey(ctx context.Context, in *GetUserMasterKeyRequest, opts ...grpc.CallOption) (*UserMasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMasterKeyResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetUserMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) WidgetNewToken(ctx context.Context, in *WidgetTokenData, opts ...grpc.CallOption) (*WidgetRawToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetRawToken)
	err := c.cc.Invoke(ctx, ConfigService_WidgetNewToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) WidgetParseToken(ctx context.Context, in *WidgetRawToken, opts ...grpc.CallOption) (*WidgetTokenData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetTokenData)
	err := c.cc.Invoke(ctx, ConfigService_WidgetParseToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) WidgetNewCode(ctx context.Context, in *WidgetCodeData, opts ...grpc.CallOption) (*WidgetRawToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetRawToken)
	err := c.cc.Invoke(ctx, ConfigService_WidgetNewCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) WidgetParseCode(ctx context.Context, in *WidgetRawToken, opts ...grpc.CallOption) (*WidgetCodeData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetCodeData)
	err := c.cc.Invoke(ctx, ConfigService_WidgetParseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) WidgetParseExpiredToken(ctx context.Context, in *WidgetRawToken, opts ...grpc.CallOption) (*WidgetTokenData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetTokenData)
	err := c.cc.Invoke(ctx, ConfigService_WidgetParseExpiredToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService — gRPC service for inter-service communication with Landing.
// Authorization: metadata header "x-service-key" must contain the service key
// stored in app_config under "svc.service_key".
type ConfigServiceServer interface {
	// GetBotConfig returns decrypted Telegram bot settings.
	GetBotConfig(context.Context, *GetBotConfigRequest) (*BotConfigResponse, error)
	GetOperBotConfig(context.Context, *GetBotConfigRequest) (*BotConfigResponse, error)
	// GetUserMasterKey returns the decrypted User MasterKey from Landing's in-memory cache.
	// The key is available only after the user has logged in at least once since the last
	// Landing restart. Returns codes.Unavailable if the key is not in cache.
	// The caller is responsible for deciding how to handle the unavailable case.
	GetUserMasterKey(context.Context, *GetUserMasterKeyRequest) (*UserMasterKeyResponse, error)
	// WidgetNewToken generates a new token for the widget_service based on the provided data.
	WidgetNewToken(context.Context, *WidgetTokenData) (*WidgetRawToken, error)
	// WidgetParseToken parses the widget_service raw token and returns the associated data.
	WidgetParseToken(context.Context, *WidgetRawToken) (*WidgetTokenData, error)
	// WidgetNewCode sign and get new widget code.
	WidgetNewCode(context.Context, *WidgetCodeData) (*WidgetRawToken, error)
	// WidgetParseCode check signature and return climes from widget code.
	WidgetParseCode(context.Context, *WidgetRawToken) (*WidgetCodeData, error)
	// WidgetParseExpiredToken parses the expired token and returns valid token
	WidgetParseExpiredToken(context.Context, *WidgetRawToken) (*WidgetTokenData, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetBotConfig(context.Context, *GetBotConfigRequest) (*BotConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetOperBotConfig(context.Context, *GetBotConfigRequest) (*BotConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperBotConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetUserMasterKey(context.Context, *GetUserMasterKeyRequest) (*UserMasterKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMasterKey not implemented")
}
func (UnimplementedConfigServiceServer) WidgetNewToken(context.Context, *WidgetTokenData) (*WidgetRawToken, error) {
	return nil, status.Error(codes.Unimplemented, "method WidgetNewToken not implemented")
}
func (UnimplementedConfigServiceServer) WidgetParseToken(context.Context, *WidgetRawToken) (*WidgetTokenData, error) {
	return nil, status.Error(codes.Unimplemented, "method WidgetParseToken not implemented")
}
func (UnimplementedConfigServiceServer) WidgetNewCode(context.Context, *WidgetCodeData) (*WidgetRawToken, error) {
	return nil, status.Error(codes.Unimplemented, "method WidgetNewCode not implemented")
}
func (UnimplementedConfigServiceServer) WidgetParseCode(context.Context, *WidgetRawToken) (*WidgetCodeData, error) {
	return nil, status.Error(codes.Unimplemented, "method WidgetParseCode not implemented")
}
func (UnimplementedConfigServiceServer) WidgetParseExpiredToken(context.Context, *WidgetRawToken) (*WidgetTokenData, error) {
	return nil, status.Error(codes.Unimplemented, "method WidgetParseExpiredToken not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we urls this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetBotConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetBotConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetBotConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetBotConfig(ctx, req.(*GetBotConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetOperBotConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetOperBotConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetOperBotConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetOperBotConfig(ctx, req.(*GetBotConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetUserMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetUserMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetUserMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetUserMasterKey(ctx, req.(*GetUserMasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WidgetNewToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetTokenData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).WidgetNewToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_WidgetNewToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).WidgetNewToken(ctx, req.(*WidgetTokenData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WidgetParseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetRawToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).WidgetParseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_WidgetParseToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).WidgetParseToken(ctx, req.(*WidgetRawToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WidgetNewCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetCodeData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).WidgetNewCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_WidgetNewCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).WidgetNewCode(ctx, req.(*WidgetCodeData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WidgetParseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetRawToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).WidgetParseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_WidgetParseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).WidgetParseCode(ctx, req.(*WidgetRawToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WidgetParseExpiredToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetRawToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).WidgetParseExpiredToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_WidgetParseExpiredToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).WidgetParseExpiredToken(ctx, req.(*WidgetRawToken))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svcpb.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBotConfig",
			Handler:    _ConfigService_GetBotConfig_Handler,
		},
		{
			MethodName: "GetOperBotConfig",
			Handler:    _ConfigService_GetOperBotConfig_Handler,
		},
		{
			MethodName: "GetUserMasterKey",
			Handler:    _ConfigService_GetUserMasterKey_Handler,
		},
		{
			MethodName: "WidgetNewToken",
			Handler:    _ConfigService_WidgetNewToken_Handler,
		},
		{
			MethodName: "WidgetParseToken",
			Handler:    _ConfigService_WidgetParseToken_Handler,
		},
		{
			MethodName: "WidgetNewCode",
			Handler:    _ConfigService_WidgetNewCode_Handler,
		},
		{
			MethodName: "WidgetParseCode",
			Handler:    _ConfigService_WidgetParseCode_Handler,
		},
		{
			MethodName: "WidgetParseExpiredToken",
			Handler:    _ConfigService_WidgetParseExpiredToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc_config.proto",
}
