// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: svc_config.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBotConfigRequest — empty request (auth via metadata).
type GetBotConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotConfigRequest) Reset() {
	*x = GetBotConfigRequest{}
	mi := &file_svc_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotConfigRequest) ProtoMessage() {}

func (x *GetBotConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBotConfigRequest) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{0}
}

// BotConfigResponse — Telegram bot settings.
type BotConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                    // Bot API token
	BotName       string                 `protobuf:"bytes,2,opt,name=bot_name,json=botName,proto3" json:"bot_name,omitempty"` // Bot username (without @)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotConfigResponse) Reset() {
	*x = BotConfigResponse{}
	mi := &file_svc_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotConfigResponse) ProtoMessage() {}

func (x *BotConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotConfigResponse.ProtoReflect.Descriptor instead.
func (*BotConfigResponse) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{1}
}

func (x *BotConfigResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BotConfigResponse) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

// GetUserMasterKeyRequest — request for a user's MasterKey.
type GetUserMasterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMasterKeyRequest) Reset() {
	*x = GetUserMasterKeyRequest{}
	mi := &file_svc_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMasterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMasterKeyRequest) ProtoMessage() {}

func (x *GetUserMasterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMasterKeyRequest.ProtoReflect.Descriptor instead.
func (*GetUserMasterKeyRequest) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserMasterKeyRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserMasterKeyResponse — raw 32-byte AES-256 MasterKey.
// Transmitted only over secured internal network (Docker bridge + service key auth).
type UserMasterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterKey     []byte                 `protobuf:"bytes,1,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"` // 32 bytes — AES-256 key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMasterKeyResponse) Reset() {
	*x = UserMasterKeyResponse{}
	mi := &file_svc_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMasterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMasterKeyResponse) ProtoMessage() {}

func (x *UserMasterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMasterKeyResponse.ProtoReflect.Descriptor instead.
func (*UserMasterKeyResponse) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{3}
}

func (x *UserMasterKeyResponse) GetMasterKey() []byte {
	if x != nil {
		return x.MasterKey
	}
	return nil
}

type WidgetTokenData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // User ID
	RespId         uint64                 `protobuf:"varint,2,opt,name=resp_id,json=respId,proto3" json:"resp_id,omitempty"`                         // Response ID
	ExpiredSeconds int64                  `protobuf:"varint,3,opt,name=expired_seconds,json=expiredSeconds,proto3" json:"expired_seconds,omitempty"` // Expiration time in seconds
	Origin         string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`                                        // Normalized browser origin
	Jti            string                 `protobuf:"bytes,5,opt,name=jti,proto3" json:"jti,omitempty"`                                              // Unique temporary token ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WidgetTokenData) Reset() {
	*x = WidgetTokenData{}
	mi := &file_svc_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetTokenData) ProtoMessage() {}

func (x *WidgetTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetTokenData.ProtoReflect.Descriptor instead.
func (*WidgetTokenData) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{4}
}

func (x *WidgetTokenData) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WidgetTokenData) GetRespId() uint64 {
	if x != nil {
		return x.RespId
	}
	return 0
}

func (x *WidgetTokenData) GetExpiredSeconds() int64 {
	if x != nil {
		return x.ExpiredSeconds
	}
	return 0
}

func (x *WidgetTokenData) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *WidgetTokenData) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

type WidgetCodeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExamKey       string                 `protobuf:"bytes,2,opt,name=exam_key,json=examKey,proto3" json:"exam_key,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NeverExpires  bool                   `protobuf:"varint,4,opt,name=never_expires,json=neverExpires,proto3" json:"never_expires,omitempty"`
	AllowedUrls   []string               `protobuf:"bytes,5,rep,name=allowed_urls,json=allowedUrls,proto3" json:"allowed_urls,omitempty"`
	Jti           string                 `protobuf:"bytes,6,opt,name=jti,proto3" json:"jti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetCodeData) Reset() {
	*x = WidgetCodeData{}
	mi := &file_svc_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetCodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetCodeData) ProtoMessage() {}

func (x *WidgetCodeData) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetCodeData.ProtoReflect.Descriptor instead.
func (*WidgetCodeData) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{5}
}

func (x *WidgetCodeData) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WidgetCodeData) GetExamKey() string {
	if x != nil {
		return x.ExamKey
	}
	return ""
}

func (x *WidgetCodeData) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *WidgetCodeData) GetNeverExpires() bool {
	if x != nil {
		return x.NeverExpires
	}
	return false
}

func (x *WidgetCodeData) GetAllowedUrls() []string {
	if x != nil {
		return x.AllowedUrls
	}
	return nil
}

func (x *WidgetCodeData) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

type WidgetRawToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Raw token for the widget
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetRawToken) Reset() {
	*x = WidgetRawToken{}
	mi := &file_svc_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetRawToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetRawToken) ProtoMessage() {}

func (x *WidgetRawToken) ProtoReflect() protoreflect.Message {
	mi := &file_svc_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetRawToken.ProtoReflect.Descriptor instead.
func (*WidgetRawToken) Descriptor() ([]byte, []int) {
	return file_svc_config_proto_rawDescGZIP(), []int{6}
}

func (x *WidgetRawToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_svc_config_proto protoreflect.FileDescriptor

const file_svc_config_proto_rawDesc = "" +
	"\n" +
	"\x10svc_config.proto\x12\x05svcpb\"\x15\n" +
	"\x13GetBotConfigRequest\"D\n" +
	"\x11BotConfigResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bbot_name\x18\x02 \x01(\tR\abotName\"2\n" +
	"\x17GetUserMasterKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"6\n" +
	"\x15UserMasterKeyResponse\x12\x1d\n" +
	"\n" +
	"master_key\x18\x01 \x01(\fR\tmasterKey\"\x96\x01\n" +
	"\x0fWidgetTokenData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\aresp_id\x18\x02 \x01(\x04R\x06respId\x12'\n" +
	"\x0fexpired_seconds\x18\x03 \x01(\x03R\x0eexpiredSeconds\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12\x10\n" +
	"\x03jti\x18\x05 \x01(\tR\x03jti\"\xbd\x01\n" +
	"\x0eWidgetCodeData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bexam_key\x18\x02 \x01(\tR\aexamKey\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12#\n" +
	"\rnever_expires\x18\x04 \x01(\bR\fneverExpires\x12!\n" +
	"\fallowed_urls\x18\x05 \x03(\tR\vallowedUrls\x12\x10\n" +
	"\x03jti\x18\x06 \x01(\tR\x03jti\"&\n" +
	"\x0eWidgetRawToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xbf\x04\n" +
	"\rConfigService\x12D\n" +
	"\fGetBotConfig\x12\x1a.svcpb.GetBotConfigRequest\x1a\x18.svcpb.BotConfigResponse\x12H\n" +
	"\x10GetOperBotConfig\x12\x1a.svcpb.GetBotConfigRequest\x1a\x18.svcpb.BotConfigResponse\x12P\n" +
	"\x10GetUserMasterKey\x12\x1e.svcpb.GetUserMasterKeyRequest\x1a\x1c.svcpb.UserMasterKeyResponse\x12?\n" +
	"\x0eWidgetNewToken\x12\x16.svcpb.WidgetTokenData\x1a\x15.svcpb.WidgetRawToken\x12A\n" +
	"\x10WidgetParseToken\x12\x15.svcpb.WidgetRawToken\x1a\x16.svcpb.WidgetTokenData\x12=\n" +
	"\rWidgetNewCode\x12\x15.svcpb.WidgetCodeData\x1a\x15.svcpb.WidgetRawToken\x12?\n" +
	"\x0fWidgetParseCode\x12\x15.svcpb.WidgetRawToken\x1a\x15.svcpb.WidgetCodeData\x12H\n" +
	"\x17WidgetParseExpiredToken\x12\x15.svcpb.WidgetRawToken\x1a\x16.svcpb.WidgetTokenDataB,Z*github.com/ikermy/air-common/pkg/rpc/protob\x06proto3"

var (
	file_svc_config_proto_rawDescOnce sync.Once
	file_svc_config_proto_rawDescData []byte
)

func file_svc_config_proto_rawDescGZIP() []byte {
	file_svc_config_proto_rawDescOnce.Do(func() {
		file_svc_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_config_proto_rawDesc), len(file_svc_config_proto_rawDesc)))
	})
	return file_svc_config_proto_rawDescData
}

var file_svc_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_svc_config_proto_goTypes = []any{
	(*GetBotConfigRequest)(nil),     // 0: svcpb.GetBotConfigRequest
	(*BotConfigResponse)(nil),       // 1: svcpb.BotConfigResponse
	(*GetUserMasterKeyRequest)(nil), // 2: svcpb.GetUserMasterKeyRequest
	(*UserMasterKeyResponse)(nil),   // 3: svcpb.UserMasterKeyResponse
	(*WidgetTokenData)(nil),         // 4: svcpb.WidgetTokenData
	(*WidgetCodeData)(nil),          // 5: svcpb.WidgetCodeData
	(*WidgetRawToken)(nil),          // 6: svcpb.WidgetRawToken
}
var file_svc_config_proto_depIdxs = []int32{
	0, // 0: svcpb.ConfigService.GetBotConfig:input_type -> svcpb.GetBotConfigRequest
	0, // 1: svcpb.ConfigService.GetOperBotConfig:input_type -> svcpb.GetBotConfigRequest
	2, // 2: svcpb.ConfigService.GetUserMasterKey:input_type -> svcpb.GetUserMasterKeyRequest
	4, // 3: svcpb.ConfigService.WidgetNewToken:input_type -> svcpb.WidgetTokenData
	6, // 4: svcpb.ConfigService.WidgetParseToken:input_type -> svcpb.WidgetRawToken
	5, // 5: svcpb.ConfigService.WidgetNewCode:input_type -> svcpb.WidgetCodeData
	6, // 6: svcpb.ConfigService.WidgetParseCode:input_type -> svcpb.WidgetRawToken
	6, // 7: svcpb.ConfigService.WidgetParseExpiredToken:input_type -> svcpb.WidgetRawToken
	1, // 8: svcpb.ConfigService.GetBotConfig:output_type -> svcpb.BotConfigResponse
	1, // 9: svcpb.ConfigService.GetOperBotConfig:output_type -> svcpb.BotConfigResponse
	3, // 10: svcpb.ConfigService.GetUserMasterKey:output_type -> svcpb.UserMasterKeyResponse
	6, // 11: svcpb.ConfigService.WidgetNewToken:output_type -> svcpb.WidgetRawToken
	4, // 12: svcpb.ConfigService.WidgetParseToken:output_type -> svcpb.WidgetTokenData
	6, // 13: svcpb.ConfigService.WidgetNewCode:output_type -> svcpb.WidgetRawToken
	5, // 14: svcpb.ConfigService.WidgetParseCode:output_type -> svcpb.WidgetCodeData
	4, // 15: svcpb.ConfigService.WidgetParseExpiredToken:output_type -> svcpb.WidgetTokenData
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_config_proto_init() }
func file_svc_config_proto_init() {
	if File_svc_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_config_proto_rawDesc), len(file_svc_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_config_proto_goTypes,
		DependencyIndexes: file_svc_config_proto_depIdxs,
		MessageInfos:      file_svc_config_proto_msgTypes,
	}.Build()
	File_svc_config_proto = out.File
	file_svc_config_proto_goTypes = nil
	file_svc_config_proto_depIdxs = nil
}
